import type { Metadata } from "next";
import { Rubik, Open_Sans } from "next/font/google";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import QueryProvider from "@/providers/QueryProvider";
import NewsLetter from "@/components/common/NewsLetter";

const rubik = Rubik({
    display: 'swap',
    variable: "--font-rubik",
    subsets: ["latin"],
});

const openSans = Open_Sans({
    display: 'swap',
    variable: "--font-open-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body
                className={`${rubik.variable} ${openSans.variable} antialiased`}
            >
                <QueryProvider>
                    <Header/>
                    <main>
                        {children}
                    </main>
                    <NewsLetter/>
                    <Footer/>
                </QueryProvider>
            </body>
        </html>
    );
}